### PR TITLE
Formatting

### PR DESCRIPTION
**Pull request by golmschenk**
Updates some simple formatting

### CODE REVIEW

**Comment by golmschenk** [comment]
Interesting. I thought I had put the tests on a separate branch. I guess I'm not entirely used to git branch manipulation yet.

**Comment by Jusctsch5** [comment]
I'm not sure what the effects will be of merging your "Merge branch 'master' into formattting". I would assume that it's not going to break anything, but it looks like it might mess up the git history of those files? 
If you pull, try doing a rebase as described in the following link:
http://kernowsoul.com/blog/2012/06/20/4-ways-to-avoid-merge-commits-in-git/

Everything else looks good though. Tests are fine too. Can you remove the merge commit and submit a new pull request?

**Comment by golmschenk** [comment]
Looking elsewhere, it looks like there's a big debate over whether a `rebase` workflow (such as that suggested in the link you gave me) or a `merge` workflow is preferred. Very simplified, it appears that the `rebase` approach leads to a more traditional branch development, but destroys local history, while the `merge` approach leads to a more complex history structure, but retains all history. I haven't looked into it enough just yet to suggest that one is better than the other. Basically, my thinking was that I wanted the latest changes from the master branch in my formatting branch, so that I could continue updating the latest stuff and have my code matching that of the master. Then, when I was ready to have my code pulled into the master branch, it would be ready to roll. Do you think I should be accomplishing this differently?

**Comment by golmschenk** [comment]
I suppose I haven't looked into either enough yet to really understand what each is about, but intuitively (to me at least) it makes sense that each branch would just split off and, whenever it needs the latest from another branch, it just takes those updates and continues on. But again, I haven't looked into it enough to know what all the downsides are.

**Comment by Jusctsch5** [comment]
My preference here is the rebase workflow, as I don't see the value in
keeping local history (like merge commits) in the master branch for this
project.
My approach is the same as you described. Here's a brief look at my
workflow:

To update my master branch:

> git pull --rebase

Then I create a working branch:

> git branch lets_do_some_work

Then I do some work and commit that work.
Then I might do some more work and commit that.
(continue until I feel like my changes are correct, tested, and reviewed)

Then I go through and rearrange my commits to my liking:

> git rebase -i $sha_of_commit_prior_to_my_first_commit

(I actually do this part periodically as well.)

When everything is kosher, then I get ready to push to origin (or whatever
my remote is called):

> git pull --rebase
> git push origin lets_do_some_work

Then I let github sort the rest of the magic out.

On Sat, Aug 22, 2015 at 9:35 PM, golmschenk notifications@github.com
wrote:

> I suppose I haven't looked into either enough yet to really understand
> what each is about, but intuitively (to me at least) it makes sense that
> each branch would just split off and, whenever it needs the latest from
> another branch, it just takes those updates and continues on. But again, I
> haven't looked into it enough to know what all the downsides are.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Wilfcastle/colonies/pull/5#issuecomment-133774604.

## 

John Schumacher

**Comment by golmschenk** [comment]
Besides the "rearranging commits" part, the two approaches seem the same. What do you use rearranging the commits for? Also, do you foresee any possible harm in me merging the master branch into other branches? It leaves the master branch unchanged, and I believe once we pull the working branch into the master branch (even if the master branch has been merged into that working branch, possibly multiple times) everything just neatly sorts itself out and our git network graph (https://github.com/Wilfcastle/colonies/network) should come out straight without any problems. Any thoughts on that?

**Comment by golmschenk** [comment]
Ah, I see. This was extremely helpful: https://www.atlassian.com/git/tutorials/merging-vs-rebasing. Based on that, it looks like rebasing is probably the nicer option (as it leaves your history a bit more linear), so long as you do it right. However, it's definitely a lot more dangerous if you do something wrong. If you'd prefer to have the linear history, I'll switch to using the rebase approach. But if how the history looks to you isn't of much importance (though it will still contain all correct information), I may stick with the merging as (to me) it's more intuitive and I don't need to worry about breaking something. Let me know.

**Comment by Jusctsch5** [comment]
The *Interactive Rebasing *section from that Atlassian link describes what
I'm talking about. I use it to squash my checkpoint commits together to
make distinct and self-contained commits.
It's probably worthwhile to familiarize yourself with the rebase workflow
now, as this is a pretty low-risk environment. Git is only dangerous if you
don't realize that you've done something bad. See documentation on 'git
reflog' if you ever get in a bind. I don't think a linear history is
terribly important for this project, so I could understand if didn't think
exploring the rebase workflow was worthwhile.

On Sat, Aug 22, 2015 at 10:54 PM, golmschenk notifications@github.com
wrote:

> Ah, I see. This was extremely helpful:
> https://www.atlassian.com/git/tutorials/merging-vs-rebasing. Based on
> that, it looks like rebasing is probably the nicer option (as it leaves
> your history a bit more linear), so long as you do it right. However, it's
> definitely a lot more dangerous if you do something wrong. If you'd prefer
> to have the linear history, I'll switch to using the rebase approach. But
> if how the history looks to you isn't of much importance (though it will
> still contain all correct information), I may stick with the merging as (to
> me) it's more intuitive and I don't need to worry about breaking something.
> Let me know.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Wilfcastle/colonies/pull/5#issuecomment-133778648.

## 

John Schumacher

**Comment by Jusctsch5** [comment]
Think about it and let me know what you think. Feel free to merge the pull
request whenever, if you decide to leave things as they are.

On Sat, Aug 22, 2015 at 11:59 PM, John Schumacher schumjs@gmail.com wrote:

> The *Interactive Rebasing *section from that Atlassian link describes
> what I'm talking about. I use it to squash my checkpoint commits together
> to make distinct and self-contained commits.
> It's probably worthwhile to familiarize yourself with the rebase workflow
> now, as this is a pretty low-risk environment. Git is only dangerous if you
> don't realize that you've done something bad. See documentation on 'git
> reflog' if you ever get in a bind. I don't think a linear history is
> terribly important for this project, so I could understand if didn't think
> exploring the rebase workflow was worthwhile.
> 
> On Sat, Aug 22, 2015 at 10:54 PM, golmschenk notifications@github.com
> wrote:
> 
> > Ah, I see. This was extremely helpful:
> > https://www.atlassian.com/git/tutorials/merging-vs-rebasing. Based on
> > that, it looks like rebasing is probably the nicer option (as it leaves
> > your history a bit more linear), so long as you do it right. However, it's
> > definitely a lot more dangerous if you do something wrong. If you'd prefer
> > to have the linear history, I'll switch to using the rebase approach. But
> > if how the history looks to you isn't of much importance (though it will
> > still contain all correct information), I may stick with the merging as (to
> > me) it's more intuitive and I don't need to worry about breaking something.
> > Let me know.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/Wilfcastle/colonies/pull/5#issuecomment-133778648.
> 
> ## 
> 
> John Schumacher

## 

John Schumacher

**Comment by golmschenk** [comment]
Enough people use the rebase approach that it's probably worthwhile to learn it. I'll give that a try for a few branches.

**Pull request closed without merging**
