### PR TITLE
Project structure

### PR DESCRIPTION
**Pull request by golmschenk**
Updates the structure of the project to move the game classes into a module.

### CODE REVIEW

**Comment by golmschenk** [comment]
I would also like to suggest that we consider moving the Python files out of `source` and into the root directory. Seeing that in Python you don't need to explicitly compile code, I don't know why it would be beneficially to keep that code in a separate folder (where it seems it may just require the use of lots of additional path information to reach anything else). However, if a good reason can be suggested to keep it in this structure, I'm happy to have it as it is.

**Comment by Jusctsch5** [comment]
It's fairly simple - there will be more than just python files involved in
this project. The directory hierarchy should reflect that.

Now, I'm not saying we should call it it 'source', perhaps 'code' would fit
better. I don't really care about the directory name, just that all of the
files included are code and not images, audio, or whatever we think we need
that is separate.

We can get around the additional path information if we need to.

On Wed, Jul 22, 2015 at 9:12 PM, golmschenk notifications@github.com
wrote:

> I would also like to suggest that we consider moving the Python files out
> of source and into the root directory. Seeing that in Python you don't
> need to explicitly compile code, I don't know why it would be beneficially
> to keep that code in a separate folder (where it seems it may just require
> the use of lots of additional path information to reach anything else).
> However, if a good reason can be suggested to keep it in this structure,
> I'm happy to have it as it is.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Wilfcastle/colonies/pull/3#issuecomment-123931258.

## 

John Schumacher

**Comment by golmschenk** [comment]
No. Not unless you try to load them both as `Piece` in the same namespace.

**Comment by Jusctsch5** [comment]
Sounds good. Feel free to merge the pull request (or I can).

**Comment by golmschenk** [comment]
I still am not completely convinced by your argument for having the `src`-like directory. A clean hierarchy is good, but I don't necessarily see the point of separating out things by file type. The Python files are required to do anything, and they don't need to have a separate compiled version of the files we need to worry about, so there doesn't need to be a `build` or the like. To me, it seems much more clear to have something along the lines of:

```
root/
    levels/
    game/
    main.py
```

Basically your still separating your code into packages, but there's not just a `py` folder that all python files are suppose to live in. This has the one additional added benefit that `root` can then be a runnable package in it's own right. So then our entire game is just prepackaged in such a way that anyone can just download the entire thing, never have to look inside, and just run `python root` to start the game.

I'm not really against having a code folder, but at the moment it still seems superfluous to me.

**Comment by Jusctsch5** [comment]
I agree with being able to simply launch the game by doing something in
root. That being said, I think it's a good idea to separate code from other
assets. I think we can accommodate both We might have to learn how to do
some python things that we don't yet know how to do.

Here are some examples from some things we're familiar with:
https://github.com/wesnoth/wesnoth (has a src/ folder)
https://github.com/Jusctsch5/ironsphererpg (has a scripts/ folder)
https://github.com/bstrie/dcss-mirror/tree/master/crawl-ref (has a source/
folder)

To see how python folks have done it, I looked at the following:
https://github.com/leereilly/games

I actually really like what this guy has done:
https://github.com/unknown-horizons/unknown-horizons

Based on his solution, here's something to consider.

root/
    levels/
    assets/
    code/
       game/
    main.py

On Fri, Jul 24, 2015 at 11:08 AM, golmschenk notifications@github.com
wrote:

> I still am not completely convinced by your argument for having the src-like
> directory. A clean hierarchy is good, but I don't necessarily see the point
> of separating out things by file type. The Python files are required to do
> anything, and they don't need to have a separate compiled version of the
> files we need to worry about, so there doesn't need to be a build or the
> like. To me, it seems much more clear to have something along the lines of:
> 
> root/
>     levels/
>     game/
>     main.py
> 
> Basically your still separating your code into packages, but there's not
> just a py folder that all python files are suppose to live in. This has
> the one additional added benefit that root can then be a runnable package
> in it's own right. So then our entire game is just prepackaged in such a
> way that anyone can just download the entire thing, never have to look
> inside, and just run python root to start the game.
> 
> I'm not really against having a code folder, but at the moment it still
> seems superfluous to me.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Wilfcastle/colonies/pull/3#issuecomment-124569061.

## 

John Schumacher

**Comment by golmschenk** [comment]
Don't worry, I know that that style of structure is common among C/C++ code and the like. It makes a lot of sense to do that there where the code needs to be compiled and the source code should be separated from the compiled stuff. I just didn't see as much of a point for such a setup in Python. In any case, the structure you just listed is good enough for me. And if we make it right it should be easy to change in the future anyway. Really, if you want to go with your `game` is a separate general package which `colonies` uses, then these should probably eventually end up in separate projects and repositories entirely. However, for now, we can keep it simple and clump it all together.

**Comment by Jusctsch5** [comment]
I still don't think you're understanding the purpose of what I'm suggesting, as it's not related to a specific programming language. Did you see the examples that I provided (which use different languages)?

In most projects, different types of things are in different directories. Code (whether it be .py/.cpp/.cxx is one of those types.

**Comment by Jusctsch5** [comment]
Also, I haven't really thought a lot about if a colonies package should exist. I'm relying on you to help take what I think makes sense from an object sense to what makes sense in terms of organization in Python. I will bring up those questions when I get there. A one-package-per-project-or-repository does sound a little odd, however.

**Comment by golmschenk** [comment]
Sorry, I don't think I clearly explained what I meant before. Yes, I saw the other projects and know that this is common practice to have a `src` directory. It even comes up frequently in Python projects. What I meant to say is that my understanding of the use of such a directory is not important in a Python project (and that those that use it in Python projects only do so because they're used to that practice in other languages as well). But in any case, the practice is still often done in Python and so I'm happy to do it. I just still don't see a lot of value in it in a Python project (as opposed to other languages which will have separate `build` locations and whatnot and therefore it's more valuable to separate the original source from the other parts). Of course, there could be other value to this structure that I just don't know about yet.

As far as the one-package-per-project-or-repository, I would think of it as the project _is_ the package. This is useful because, say, I'm another developer who wants to make use of our `game` package, it makes more sense to me that I would just have to clone down the `game` project and then with no other work I can just directly use `import game` in my code with no other fuss (and without additional parts like the `colonies` part coming with it). But again, I think that will only be important if we get to a point that we feel the `game` package is good enough to stand on its own and can be used in other projects.

**Comment by Jusctsch5** [comment]
Roger. I find value on segregating assets here purely for organizational
purposes. It will help me to keep the code in its own directory.

I understand now. My preference for this project will be keep multiple
packages within our one project (assuming we create multiple packages).
There's an obvious benefit here in regards to simplicity of use in not
having to manage multiple repositories. That being said, we could then
easily spin off these packages into their own projects if we want. We could
also use submodules within github to keep things better organized in a
single project-space.

https://help.github.com/articles/using-submodules-with-pages/

On Fri, Jul 24, 2015 at 3:27 PM, golmschenk notifications@github.com
wrote:

> Sorry, I don't think I clearly explained what I meant before. Yes, I saw
> the other projects and know that this is common practice to have a src
> directory. It even comes up frequently in Python projects. What I meant to
> say is that my understanding of the use of such a directory is not
> important in a Python project (and that those that use it in Python
> projects only do so because they're used to that practice in other
> languages as well). But in any case, the practice is still often done in
> Python and so I'm happy to do it. I just still don't see a lot of value in
> it in a Python project (as opposed to other languages which will have
> separate build locations and whatnot and therefore it's more valuable to
> separate the original source from the other parts). Of course, there could
> be other value to this structure that I just don't know about yet.
> 
> As far as the one-package-per-project-or-repository, I would think of it
> as the project _is_ the package. This is useful because, say, I'm another
> developer who wants to make use of our game package, it makes more sense
> to me that I would just have to clone down the game project and then with
> no other work I can just directly use import game in my code with no
> other fuss (and without additional parts like the colonies part coming
> with it). But again, I think that will only be important if we get to a
> point that we feel the game package is good enough to stand on its own
> and can be used in other projects.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Wilfcastle/colonies/pull/3#issuecomment-124711275.

## 

John Schumacher

**Comment by golmschenk** [comment]
Fair enough. And I agree about keeping it a single project for the moment at least.

**Comment by Jusctsch5** [comment]
How do you run this, and what environment? I have python installed for windows, and ran into the following issue:

> main.py ..\levels\sample_level_1
> Traceback (most recent call last):
>   File "F:\git\colonies\source\main.py", line 2, in <module>
>     from source.game.board import Board
> ImportError: No module named 'source'

Removing the "source." from "source.foo..." fixed my import error. Is that the general solution - or is my problem specific to my environment?

**Comment by golmschenk** [comment]
I bet I know the problem but I'm not entirely sure (and am not able to access my computer right now to check). I bet it's because when I run any of my code from my IDE it always runs it from the root directory of the project. This means the root directory of the project is added to the `PYTHON_PATH` during the running which means that the path to the game package is under `source`. Where if you were running main directly from its own directory then the package isn't under the `source` package. Either you could tell your IDE to run all code from root, or Python also supports relative imports and we could try using that.

**Comment by golmschenk** [comment]
Ah, the other case works for me as well (i.e. just `game.foo`). I thought there was an error with this, but my IDE can run both approaches without a problem.

**Pull request merged**
